[workspace]
members = [
    "action-executor",
    "gcloud",
    "trigger-interpreter",
    "trigger-system",
    "process",
    "protocol",
    "toolkit",
    "plugin-core",
    "plugin-host",
    "plugin-builtins/directory_watch",
    "plugin-builtins/notify",
    "rulecreator"
]
