ignore:
  - "trigger-system/src/iface_impl/**"
  - "gcloud/**.rs"
  - "plugin-builtins/**.rs"
  - "trigger-interpreter/src/tests/mock.rs"
  - "trigger-system/src/tests/mock.rs"
  - "plugin-core/**.rs"
  - "**/main.rs"
