[package]
name = "action-executor"
version = "0.1.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
gcloud = {path = "../gcloud"}
log = "0.4"
protocol = {path = "../protocol"}
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
toolkit = {path = "../toolkit"}
