name: CI

on:
  push: {}

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Mount build cache
        uses: actions/cache@v1
        with:
          path: "target"
          key: shift-cache

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features